server:
  port: 8080

logging:
  file:
    path: ./logs

spring:

  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: r8meservice
      repositories:
        type: auto
  cache:
    type: redis

jwt:
  secret: ${JWT_TOKEN:tomeczekwodeczka}

redis:
  host:
    url: localhost
    port: 6379


config:
  apiKey: ${APIKEY:defaultvalue}
  address: localhost
  port: 8080
  url: localhost:8080/activate/
  email: czarny.grzybiarz@gmail.com
cache:
  timeout: 60
