server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: keepmeawake
      repositories:
        type: auto
  cache:
    type: redis

jwt:
  secret: ${JWT_TOKEN:tomeczekwodeczka}

redis:
  host:
    url: localhost
    port: 6379


config:
  apiKey: ${APIKEY:defaultvalue}
  from: welcome@keepmeawake.com
  domain: ak.keepmeawake.com
  address: localhost
  port: 8080


cache:
  timeout: 60