spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: keepmeawake
      repositories:
        type: auto
  cache:
    type: redis

jwt:
  secret: ${JWT_TOKEN:tomeczekwodeczka}

redis:
  host:
    url: localhost
    port: 6379
