version: '3.7'
services:
  r8meuserservice-app:
    image: 337703985776.dkr.ecr.us-east-2.amazonaws.com/userr8meservice:0.0.3-SNAPSHOT
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://r8meuserservice-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=r8meuserservice
      - SPRING_REDIS_HOST=r8meuserservice-redis
      - JWT_SECRET=tomeczekwodeczka
      - S3_BUCKETS_PHOTO=r8me-avatars-bucket
      - CONFIG_URL=172.31.41.188:8080/activate/
      - CONFIG_EMAIL=czarny.grzybiarz@gmail.com
      - SPRING_PROFILES_ACTIVE=dev,log-web,mongo-cluster,admin-ui
      - AWS_ACCESSKEY=${ACCESS_KEY}
      - AWS_SECRETKEY=${SECRET_KEY}

    restart: on-failure
    volumes:
      - ./logs:/tmp/logs
    ports:
      - 8080:8080
  r8meuserservice-mongodb:
    restart: on-failure
    image: mongo:4.0.12
    ports:
      - '27017:27017'
    volumes:
      - ./mongodbdata/:/data/db/

  r8meuserservice-redis:
    restart: on-failure
    image: 'bitnami/redis:latest'
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
