version: '3'
services:
  r8meuserservice-app:
    image: docker.pkg.github.com/akulinski/userr8meservice/app:0.0.3-SNAPSHOT
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://r8meuserservice-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=r8meuserservice
      - SPRING_REDIS_HOST=r8meuserservice-redis
      - JWT_SECRET=tomeczekwodeczka
      - S3_BUCKETS_PHOTO=r8me-avatars-bucket
      - CONFIG_URL=172.31.41.188:8080/activate/
      - CONFIG_EMAIL=czarny.grzybiarz@gmail.com
      - SPRING_PROFILES_ACTIVE=dev,log-web,mongo-cluster,admin-ui
      - AWS_ACCESSKEY=${ACCESS_KEY}
      - AWS_SECRETKEY=${SECRET_KEY}
    networks:
      - userr8me
      - api
    restart: on-failure
    volumes:
      - /var/log/userr8meservice/logs:/tmp/logs
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 1.5G
        reservations:
          cpus: '1'
          memory: 1G

  r8meuserservice-mongodb:
    restart: on-failure
    image: mongo:4.0.12
    networks:
      - userr8me
    ports:
      - '27017:27017'
    volumes:
      - /var/mongo/data:/data/db/
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1.5G
        reservations:
          cpus: '1.5'
          memory: 1G

  r8meuserservice-redis:
    restart: on-failure
    image: bitnami/redis:5.0-centos-7
    volumes:
      - /var/data/redis:/bitnami/redis/data
    networks:
      - userr8me
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  r8meuserservice-rabbitmq:
      image: 'bitnami/rabbitmq:3.8'
      environment:
        RABBITMQ_USERNAME: ${RABBITMQ_USER:-user}
        RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-user}
      networks:
        - userr8me
      ports:
        - "4369:4369"
        - "5672:5672"
        - "25672:25672"
        - "15672:15672"
      volumes:
        - /var/data/rabbit/:/data/db/
      deploy:
        resources:
          limits:
            cpus: '1'
            memory: 512M

  r8meuserservice-consul-agent-1: &consul-agent
      image: consul:latest
      networks:
        - userr8me
      command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0"

  r8meuserservice-consul-agent-2:
      <<: *consul-agent

  r8meuserservice-consul-agent-3:
      <<: *consul-agent

  r8meuserservice-consul-server-1: &consul-server
      <<: *consul-agent
      command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"

  r8meuserservice-consul-server-2:
      <<: *consul-server

  r8meuserservice-consul-server-bootstrap:
      <<: *consul-agent
      ports:
        - "8400:8400"
        - "8500:8500"
        - "8600:8600"
        - "8600:8600/udp"
      command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0"

networks:
  userr8me:
    driver: overlay
  api:
