version: '2'
services:
  r8meservice-mongodb:
    image: mongo:4.0.12
    ports:
      - '27017:27017'
    command: mongos --configdb r8meservice-mongodb-config
  r8meservice-mongodb-node:
    build:
      context: .
      dockerfile: mongodb/MongoDB.Dockerfile
    command: mongod --replSet rs1 --noprealloc --smallfiles
  r8meservice-mongodb-config:
    image: mongo:4.0.12
    container_name: r8meservice-mongodb-config
    command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
