version: '2'

services:
  rabbitmq:
    image: 'bitnami/rabbitmq:3.8'
    environment:
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=user
    network_mode: host
    ports:
      - '4369:4369'
      - '5672:5672'
      - '6379:6379'
      - '25672:25672'
      - '15672:15672'
    volumes:
      - ./rabbit/:/data/db/
