server:
  port: 8080

logging:
  file:
    path: ./logs

spring:
  application:
    name: userr8meservice

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${random.value}

  redis:
    host: localhost
    port: 6379
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: r8meservice
      repositories:
        type: auto
  cache:
    type: redis
  jta:
    atomikos:
      properties:
        default-max-wait-time-on-shutdown:

jwt:
  secret: ${JWT_TOKEN:tomeczekwodeczka}



config:
  url: localhost:8080/activate/
  email: czarny.grzybiarz@gmail.com
cache:
  timeout: 60


aws:
  accessKey: ${ACCESS_KEY}
  secretKey: ${SECRET_KEY}

s3:
  buckets:
    photo: r8me-avatars-bucket
