apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: keepmeawake-mongodb
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: keepmeawake-mongodb
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - name: mongo
          image: mongo:4.0.9
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: data
              mountPath: /data/db/
---
apiVersion: v1
kind: Service
metadata:
  name: keepmeawake-mongodb
  namespace: default
spec:
  selector:
    app: keepmeawake-mongodb
  ports:
    - port: 27017
