apiVersion: v1
kind: Secret
metadata:
  name: registrypullsecret
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJkb2NrZXIucGtnLmdpdGh1Yi5jb20iOiB7fQoJfSwKCSJIdHRwSGVhZGVycyI6IHsKCQkiVXNlci1BZ2VudCI6ICJEb2NrZXItQ2xpZW50LzE5LjAzLjIgKGxpbnV4KSIKCX0sCgkiY3JlZHNTdG9yZSI6ICJzZWNyZXRzZXJ2aWNlIgp9

type: kubernetes.io/dockerconfigjson
